llamafactory-cli train \
    --stage sft \
    --do_train True \
    --model_name_or_path /root/autodl-tmp/Qwen1.5-0.5B-Chat \
    --preprocessing_num_workers 16 \
    --finetuning_type lora \
    --template qwen \
    --flash_attn auto \
    --dataset_dir /root/LLaMA-Factory-main/data \
    --dataset DR, dreaddit, Irf, MultiWD, SAD \
    --cutoff_len 512 \
    --learning_rate 5e-05 \
    --num_train_epochs 15.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 5 \
    --save_steps 500 \
    --warmup_steps 0 \
    --packing False \
    --report_to wandb \
    --output_dir saves/Qwen1.5-0.5B-Chat/lora/train_2025-07-02-15-10-43 \
    --bf16 True \
    --plot_loss True \
    --trust_remote_code True \
    --ddp_timeout 180000000 \
    --include_num_input_tokens_seen True \
    --optim adamw_torch \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0 \
    --lora_target all